# Tinycast launcher, third-party tap. Needs macOS 26 or newer.
tap "abue-ammar/tinycast"

brew "bat"
brew "fd"
brew "fzf"
brew "git"
brew "gnupg"
brew "htop"
brew "ripgrep"
brew "tmux"
brew "vim"
brew "zoxide"

# Apple silicon build; Intel Macs use "tinycast-universal"
cask "tinycast"
